### Recuperar todas las películas
GET http://localhost:3000/movies

### Recuperar una película por id (AVATAR)
GET http://localhost:3000/movies/6a360a18-c645-4b47-9a7b-2a71babbf3e0

### Recuperar todas las películas por un género
GET http://localhost:3000/movies?genre=Terror